server:
  port: 8201
spring:
  application:
    name: user-service
  profiles:
    active: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

mybatis:
  typeAliasesPackage: com.ssx.entity
  mapperLocations: classpath:mapper/*.xml



